GET http://localhost:6060

###
POST  http://localhost:6060/in/login
Content-Type: application/json

{
    "email":"nashri@sapi.com",
    "password":"nashri"
}
###
POST  http://localhost:6060/in/register
Content-Type: application/json

{
    "username":"nashri",
    "email":"nashri@sapi.com",
    "password":"nashri"
}
###
GET  http://localhost:6060/pf/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFzaHJp.ML-nc3hlFpACj9X7R6MslRUEI1biAv5xZhuUUEv2rZs

