GET http://localhost:6060

###
POST  http://localhost:6060/in/login
Content-Type: application/json

{
    "email":"ss@sapi.com",
    "password":"sapi"
}
###
POST  http://localhost:6060/in/register
Content-Type: application/json

{
    "username":"nashri",
    "email":"nashri@sapi.com",
    "password":"nashri"
}